//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZTS.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class GateEntities : DbContext
    {
        public GateEntities()
            : base("name=GateEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Ticket> Tickets { get; set; }
        public DbSet<Transaction> Transactions { get; set; }
        public DbSet<TransactionDetail> TransactionDetails { get; set; }
        public DbSet<Turnstile> Turnstiles { get; set; }
        public DbSet<TurnStileServer> TurnStileServers { get; set; }
    
        public virtual ObjectResult<GetTicketBy_TDID_Result> GetTicketBy_TDID(Nullable<long> tdid)
        {
            var tdidParameter = tdid.HasValue ?
                new ObjectParameter("tdid", tdid) :
                new ObjectParameter("tdid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTicketBy_TDID_Result>("GetTicketBy_TDID", tdidParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> GetTicketByQr(Nullable<long> qr)
        {
            var qrParameter = qr.HasValue ?
                new ObjectParameter("qr", qr) :
                new ObjectParameter("qr", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GetTicketByQr", qrParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> UpdateTicketby_No(Nullable<long> qr)
        {
            var qrParameter = qr.HasValue ?
                new ObjectParameter("qr", qr) :
                new ObjectParameter("qr", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("UpdateTicketby_No", qrParameter);
        }
    }
}
