//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZTS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public string Id { get; set; }
        public string TicketNo { get; set; }
        public long TransactionDetailId { get; set; }
        public bool Status { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> EnteranceDate { get; set; }
        public string Category { get; set; }
        public Nullable<long> ReadCount { get; set; }
        public string UserDefinded { get; set; }
    
        public virtual TransactionDetail TransactionDetail { get; set; }
    }
}
