//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZTS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionDetail
    {
        public TransactionDetail()
        {
            this.Tickets = new HashSet<Ticket>();
        }
    
        public long Id { get; set; }
        public string TransactionId { get; set; }
        public Nullable<long> ProductId { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<long> UnitPrice { get; set; }
        public decimal DiscountRate { get; set; }
        public decimal TaxRate { get; set; }
        public Nullable<long> TotalAmount { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<long> ConsignmentPrice { get; set; }
        public Nullable<bool> IsConsignmentPaid { get; set; }
        public Nullable<bool> IsFOC { get; set; }
        public Nullable<long> SellingPrice { get; set; }
    
        public virtual ICollection<Ticket> Tickets { get; set; }
        public virtual Transaction Transaction { get; set; }
    }
}
