//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gate4.Watch.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public long Id { get; set; }
        public string TicketNo { get; set; }
        public long TransactionDetailId { get; set; }
        public bool Status { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> EnteranceDate { get; set; }
        public string Category { get; set; }
        public Nullable<long> ReadCount { get; set; }
        public string UserDefinded { get; set; }
        public Nullable<bool> isDelete { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> RePrint { get; set; }
        public string PlaceStatus { get; set; }
    }
}
